fixtures:
  repositories:
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '2.1.0'
    puppi:
      repo: 'https://github.com/example42/puppi.git'
      ref: 'v2.1.13'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
  symlinks:
    java: "#{source_dir}"
